package Triton.ExternProto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Replacement.proto

public final class GrSimReplacement {
  private GrSimReplacement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface grSim_RobotReplacementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_RobotReplacement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>required double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>required double y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>required double y = 2;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>required double dir = 3;</code>
     * @return Whether the dir field is set.
     */
    boolean hasDir();
    /**
     * <code>required double dir = 3;</code>
     * @return The dir.
     */
    double getDir();

    /**
     * <code>required uint32 id = 4;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 4;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required bool yellowteam = 5;</code>
     * @return Whether the yellowteam field is set.
     */
    boolean hasYellowteam();
    /**
     * <code>required bool yellowteam = 5;</code>
     * @return The yellowteam.
     */
    boolean getYellowteam();

    /**
     * <code>optional bool turnon = 6;</code>
     * @return Whether the turnon field is set.
     */
    boolean hasTurnon();
    /**
     * <code>optional bool turnon = 6;</code>
     * @return The turnon.
     */
    boolean getTurnon();
  }
  /**
   * Protobuf type {@code grSim_RobotReplacement}
   */
  public  static final class grSim_RobotReplacement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_RobotReplacement)
      grSim_RobotReplacementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_RobotReplacement.newBuilder() to construct.
    private grSim_RobotReplacement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_RobotReplacement() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_RobotReplacement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_RobotReplacement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              dir_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              id_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              yellowteam_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              turnon_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimReplacement.grSim_RobotReplacement.class, GrSimReplacement.grSim_RobotReplacement.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>required double x = 1;</code>
     * @return Whether the x field is set.
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double x = 1;</code>
     * @return The x.
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>required double y = 2;</code>
     * @return Whether the y field is set.
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double y = 2;</code>
     * @return The y.
     */
    public double getY() {
      return y_;
    }

    public static final int DIR_FIELD_NUMBER = 3;
    private double dir_;
    /**
     * <code>required double dir = 3;</code>
     * @return Whether the dir field is set.
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double dir = 3;</code>
     * @return The dir.
     */
    public double getDir() {
      return dir_;
    }

    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    /**
     * <code>required uint32 id = 4;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required uint32 id = 4;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int YELLOWTEAM_FIELD_NUMBER = 5;
    private boolean yellowteam_;
    /**
     * <code>required bool yellowteam = 5;</code>
     * @return Whether the yellowteam field is set.
     */
    public boolean hasYellowteam() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool yellowteam = 5;</code>
     * @return The yellowteam.
     */
    public boolean getYellowteam() {
      return yellowteam_;
    }

    public static final int TURNON_FIELD_NUMBER = 6;
    private boolean turnon_;
    /**
     * <code>optional bool turnon = 6;</code>
     * @return Whether the turnon field is set.
     */
    public boolean hasTurnon() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool turnon = 6;</code>
     * @return The turnon.
     */
    public boolean getTurnon() {
      return turnon_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYellowteam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, dir_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, id_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, yellowteam_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(6, turnon_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, dir_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, id_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, yellowteam_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, turnon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimReplacement.grSim_RobotReplacement)) {
        return super.equals(obj);
      }
      GrSimReplacement.grSim_RobotReplacement other = (GrSimReplacement.grSim_RobotReplacement) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (java.lang.Double.doubleToLongBits(getX())
            != java.lang.Double.doubleToLongBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (java.lang.Double.doubleToLongBits(getY())
            != java.lang.Double.doubleToLongBits(
                other.getY())) return false;
      }
      if (hasDir() != other.hasDir()) return false;
      if (hasDir()) {
        if (java.lang.Double.doubleToLongBits(getDir())
            != java.lang.Double.doubleToLongBits(
                other.getDir())) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasYellowteam() != other.hasYellowteam()) return false;
      if (hasYellowteam()) {
        if (getYellowteam()
            != other.getYellowteam()) return false;
      }
      if (hasTurnon() != other.hasTurnon()) return false;
      if (hasTurnon()) {
        if (getTurnon()
            != other.getTurnon()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getX()));
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getY()));
      }
      if (hasDir()) {
        hash = (37 * hash) + DIR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDir()));
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasYellowteam()) {
        hash = (37 * hash) + YELLOWTEAM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getYellowteam());
      }
      if (hasTurnon()) {
        hash = (37 * hash) + TURNON_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getTurnon());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_RobotReplacement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimReplacement.grSim_RobotReplacement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_RobotReplacement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_RobotReplacement)
        GrSimReplacement.grSim_RobotReplacementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimReplacement.grSim_RobotReplacement.class, GrSimReplacement.grSim_RobotReplacement.Builder.class);
      }

      // Construct using GrSimReplacement.grSim_RobotReplacement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        dir_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        yellowteam_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        turnon_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_RobotReplacement getDefaultInstanceForType() {
        return GrSimReplacement.grSim_RobotReplacement.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimReplacement.grSim_RobotReplacement build() {
        GrSimReplacement.grSim_RobotReplacement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_RobotReplacement buildPartial() {
        GrSimReplacement.grSim_RobotReplacement result = new GrSimReplacement.grSim_RobotReplacement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dir_ = dir_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.yellowteam_ = yellowteam_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.turnon_ = turnon_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimReplacement.grSim_RobotReplacement) {
          return mergeFrom((GrSimReplacement.grSim_RobotReplacement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimReplacement.grSim_RobotReplacement other) {
        if (other == GrSimReplacement.grSim_RobotReplacement.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasDir()) {
          setDir(other.getDir());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasYellowteam()) {
          setYellowteam(other.getYellowteam());
        }
        if (other.hasTurnon()) {
          setTurnon(other.getTurnon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasDir()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasYellowteam()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimReplacement.grSim_RobotReplacement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimReplacement.grSim_RobotReplacement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>required double x = 1;</code>
       * @return Whether the x field is set.
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double x = 1;</code>
       * @return The x.
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>required double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>required double y = 2;</code>
       * @return Whether the y field is set.
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double y = 2;</code>
       * @return The y.
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>required double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double dir_ ;
      /**
       * <code>required double dir = 3;</code>
       * @return Whether the dir field is set.
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double dir = 3;</code>
       * @return The dir.
       */
      public double getDir() {
        return dir_;
      }
      /**
       * <code>required double dir = 3;</code>
       * @param value The dir to set.
       * @return This builder for chaining.
       */
      public Builder setDir(double value) {
        bitField0_ |= 0x00000004;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double dir = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dir_ = 0D;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required uint32 id = 4;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required uint32 id = 4;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 4;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000008;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean yellowteam_ ;
      /**
       * <code>required bool yellowteam = 5;</code>
       * @return Whether the yellowteam field is set.
       */
      public boolean hasYellowteam() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bool yellowteam = 5;</code>
       * @return The yellowteam.
       */
      public boolean getYellowteam() {
        return yellowteam_;
      }
      /**
       * <code>required bool yellowteam = 5;</code>
       * @param value The yellowteam to set.
       * @return This builder for chaining.
       */
      public Builder setYellowteam(boolean value) {
        bitField0_ |= 0x00000010;
        yellowteam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool yellowteam = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYellowteam() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yellowteam_ = false;
        onChanged();
        return this;
      }

      private boolean turnon_ ;
      /**
       * <code>optional bool turnon = 6;</code>
       * @return Whether the turnon field is set.
       */
      public boolean hasTurnon() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool turnon = 6;</code>
       * @return The turnon.
       */
      public boolean getTurnon() {
        return turnon_;
      }
      /**
       * <code>optional bool turnon = 6;</code>
       * @param value The turnon to set.
       * @return This builder for chaining.
       */
      public Builder setTurnon(boolean value) {
        bitField0_ |= 0x00000020;
        turnon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool turnon = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTurnon() {
        bitField0_ = (bitField0_ & ~0x00000020);
        turnon_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_RobotReplacement)
    }

    // @@protoc_insertion_point(class_scope:grSim_RobotReplacement)
    private static final GrSimReplacement.grSim_RobotReplacement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimReplacement.grSim_RobotReplacement();
    }

    public static GrSimReplacement.grSim_RobotReplacement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_RobotReplacement>
        PARSER = new com.google.protobuf.AbstractParser<grSim_RobotReplacement>() {
      @java.lang.Override
      public grSim_RobotReplacement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_RobotReplacement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_RobotReplacement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_RobotReplacement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimReplacement.grSim_RobotReplacement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface grSim_BallReplacementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_BallReplacement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>optional double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>optional double y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>optional double y = 2;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>optional double vx = 3;</code>
     * @return Whether the vx field is set.
     */
    boolean hasVx();
    /**
     * <code>optional double vx = 3;</code>
     * @return The vx.
     */
    double getVx();

    /**
     * <code>optional double vy = 4;</code>
     * @return Whether the vy field is set.
     */
    boolean hasVy();
    /**
     * <code>optional double vy = 4;</code>
     * @return The vy.
     */
    double getVy();
  }
  /**
   * Protobuf type {@code grSim_BallReplacement}
   */
  public  static final class grSim_BallReplacement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_BallReplacement)
      grSim_BallReplacementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_BallReplacement.newBuilder() to construct.
    private grSim_BallReplacement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_BallReplacement() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_BallReplacement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_BallReplacement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              vx_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              vy_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimReplacement.internal_static_grSim_BallReplacement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimReplacement.grSim_BallReplacement.class, GrSimReplacement.grSim_BallReplacement.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>optional double x = 1;</code>
     * @return Whether the x field is set.
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional double x = 1;</code>
     * @return The x.
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>optional double y = 2;</code>
     * @return Whether the y field is set.
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double y = 2;</code>
     * @return The y.
     */
    public double getY() {
      return y_;
    }

    public static final int VX_FIELD_NUMBER = 3;
    private double vx_;
    /**
     * <code>optional double vx = 3;</code>
     * @return Whether the vx field is set.
     */
    public boolean hasVx() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double vx = 3;</code>
     * @return The vx.
     */
    public double getVx() {
      return vx_;
    }

    public static final int VY_FIELD_NUMBER = 4;
    private double vy_;
    /**
     * <code>optional double vy = 4;</code>
     * @return Whether the vy field is set.
     */
    public boolean hasVy() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double vy = 4;</code>
     * @return The vy.
     */
    public double getVy() {
      return vy_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, vx_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, vy_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, vx_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, vy_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimReplacement.grSim_BallReplacement)) {
        return super.equals(obj);
      }
      GrSimReplacement.grSim_BallReplacement other = (GrSimReplacement.grSim_BallReplacement) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (java.lang.Double.doubleToLongBits(getX())
            != java.lang.Double.doubleToLongBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (java.lang.Double.doubleToLongBits(getY())
            != java.lang.Double.doubleToLongBits(
                other.getY())) return false;
      }
      if (hasVx() != other.hasVx()) return false;
      if (hasVx()) {
        if (java.lang.Double.doubleToLongBits(getVx())
            != java.lang.Double.doubleToLongBits(
                other.getVx())) return false;
      }
      if (hasVy() != other.hasVy()) return false;
      if (hasVy()) {
        if (java.lang.Double.doubleToLongBits(getVy())
            != java.lang.Double.doubleToLongBits(
                other.getVy())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getX()));
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getY()));
      }
      if (hasVx()) {
        hash = (37 * hash) + VX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVx()));
      }
      if (hasVy()) {
        hash = (37 * hash) + VY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVy()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_BallReplacement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_BallReplacement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_BallReplacement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimReplacement.grSim_BallReplacement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_BallReplacement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_BallReplacement)
        GrSimReplacement.grSim_BallReplacementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimReplacement.internal_static_grSim_BallReplacement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimReplacement.grSim_BallReplacement.class, GrSimReplacement.grSim_BallReplacement.Builder.class);
      }

      // Construct using GrSimReplacement.grSim_BallReplacement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        vx_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        vy_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimReplacement.internal_static_grSim_BallReplacement_descriptor;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_BallReplacement getDefaultInstanceForType() {
        return GrSimReplacement.grSim_BallReplacement.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimReplacement.grSim_BallReplacement build() {
        GrSimReplacement.grSim_BallReplacement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_BallReplacement buildPartial() {
        GrSimReplacement.grSim_BallReplacement result = new GrSimReplacement.grSim_BallReplacement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.vx_ = vx_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.vy_ = vy_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimReplacement.grSim_BallReplacement) {
          return mergeFrom((GrSimReplacement.grSim_BallReplacement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimReplacement.grSim_BallReplacement other) {
        if (other == GrSimReplacement.grSim_BallReplacement.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasVx()) {
          setVx(other.getVx());
        }
        if (other.hasVy()) {
          setVy(other.getVy());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimReplacement.grSim_BallReplacement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimReplacement.grSim_BallReplacement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>optional double x = 1;</code>
       * @return Whether the x field is set.
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional double x = 1;</code>
       * @return The x.
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>optional double y = 2;</code>
       * @return Whether the y field is set.
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional double y = 2;</code>
       * @return The y.
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double vx_ ;
      /**
       * <code>optional double vx = 3;</code>
       * @return Whether the vx field is set.
       */
      public boolean hasVx() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional double vx = 3;</code>
       * @return The vx.
       */
      public double getVx() {
        return vx_;
      }
      /**
       * <code>optional double vx = 3;</code>
       * @param value The vx to set.
       * @return This builder for chaining.
       */
      public Builder setVx(double value) {
        bitField0_ |= 0x00000004;
        vx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vx = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVx() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vx_ = 0D;
        onChanged();
        return this;
      }

      private double vy_ ;
      /**
       * <code>optional double vy = 4;</code>
       * @return Whether the vy field is set.
       */
      public boolean hasVy() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional double vy = 4;</code>
       * @return The vy.
       */
      public double getVy() {
        return vy_;
      }
      /**
       * <code>optional double vy = 4;</code>
       * @param value The vy to set.
       * @return This builder for chaining.
       */
      public Builder setVy(double value) {
        bitField0_ |= 0x00000008;
        vy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vy = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        vy_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_BallReplacement)
    }

    // @@protoc_insertion_point(class_scope:grSim_BallReplacement)
    private static final GrSimReplacement.grSim_BallReplacement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimReplacement.grSim_BallReplacement();
    }

    public static GrSimReplacement.grSim_BallReplacement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_BallReplacement>
        PARSER = new com.google.protobuf.AbstractParser<grSim_BallReplacement>() {
      @java.lang.Override
      public grSim_BallReplacement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_BallReplacement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_BallReplacement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_BallReplacement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimReplacement.grSim_BallReplacement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface grSim_ReplacementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_Replacement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     * @return Whether the ball field is set.
     */
    boolean hasBall();
    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     * @return The ball.
     */
    GrSimReplacement.grSim_BallReplacement getBall();
    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     */
    GrSimReplacement.grSim_BallReplacementOrBuilder getBallOrBuilder();

    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    java.util.List<GrSimReplacement.grSim_RobotReplacement> 
        getRobotsList();
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    GrSimReplacement.grSim_RobotReplacement getRobots(int index);
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    int getRobotsCount();
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    java.util.List<? extends GrSimReplacement.grSim_RobotReplacementOrBuilder> 
        getRobotsOrBuilderList();
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    GrSimReplacement.grSim_RobotReplacementOrBuilder getRobotsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code grSim_Replacement}
   */
  public  static final class grSim_Replacement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_Replacement)
      grSim_ReplacementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_Replacement.newBuilder() to construct.
    private grSim_Replacement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_Replacement() {
      robots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_Replacement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_Replacement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              GrSimReplacement.grSim_BallReplacement.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = ball_.toBuilder();
              }
              ball_ = input.readMessage(GrSimReplacement.grSim_BallReplacement.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ball_);
                ball_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                robots_ = new java.util.ArrayList<GrSimReplacement.grSim_RobotReplacement>();
                mutable_bitField0_ |= 0x00000002;
              }
              robots_.add(
                  input.readMessage(GrSimReplacement.grSim_RobotReplacement.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          robots_ = java.util.Collections.unmodifiableList(robots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimReplacement.internal_static_grSim_Replacement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimReplacement.grSim_Replacement.class, GrSimReplacement.grSim_Replacement.Builder.class);
    }

    private int bitField0_;
    public static final int BALL_FIELD_NUMBER = 1;
    private GrSimReplacement.grSim_BallReplacement ball_;
    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     * @return Whether the ball field is set.
     */
    public boolean hasBall() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     * @return The ball.
     */
    public GrSimReplacement.grSim_BallReplacement getBall() {
      return ball_ == null ? GrSimReplacement.grSim_BallReplacement.getDefaultInstance() : ball_;
    }
    /**
     * <code>optional .grSim_BallReplacement ball = 1;</code>
     */
    public GrSimReplacement.grSim_BallReplacementOrBuilder getBallOrBuilder() {
      return ball_ == null ? GrSimReplacement.grSim_BallReplacement.getDefaultInstance() : ball_;
    }

    public static final int ROBOTS_FIELD_NUMBER = 2;
    private java.util.List<GrSimReplacement.grSim_RobotReplacement> robots_;
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    public java.util.List<GrSimReplacement.grSim_RobotReplacement> getRobotsList() {
      return robots_;
    }
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    public java.util.List<? extends GrSimReplacement.grSim_RobotReplacementOrBuilder> 
        getRobotsOrBuilderList() {
      return robots_;
    }
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    public int getRobotsCount() {
      return robots_.size();
    }
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    public GrSimReplacement.grSim_RobotReplacement getRobots(int index) {
      return robots_.get(index);
    }
    /**
     * <code>repeated .grSim_RobotReplacement robots = 2;</code>
     */
    public GrSimReplacement.grSim_RobotReplacementOrBuilder getRobotsOrBuilder(
        int index) {
      return robots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRobotsCount(); i++) {
        if (!getRobots(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBall());
      }
      for (int i = 0; i < robots_.size(); i++) {
        output.writeMessage(2, robots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBall());
      }
      for (int i = 0; i < robots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, robots_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimReplacement.grSim_Replacement)) {
        return super.equals(obj);
      }
      GrSimReplacement.grSim_Replacement other = (GrSimReplacement.grSim_Replacement) obj;

      if (hasBall() != other.hasBall()) return false;
      if (hasBall()) {
        if (!getBall()
            .equals(other.getBall())) return false;
      }
      if (!getRobotsList()
          .equals(other.getRobotsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBall()) {
        hash = (37 * hash) + BALL_FIELD_NUMBER;
        hash = (53 * hash) + getBall().hashCode();
      }
      if (getRobotsCount() > 0) {
        hash = (37 * hash) + ROBOTS_FIELD_NUMBER;
        hash = (53 * hash) + getRobotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimReplacement.grSim_Replacement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_Replacement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_Replacement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimReplacement.grSim_Replacement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimReplacement.grSim_Replacement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_Replacement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_Replacement)
        GrSimReplacement.grSim_ReplacementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimReplacement.internal_static_grSim_Replacement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimReplacement.grSim_Replacement.class, GrSimReplacement.grSim_Replacement.Builder.class);
      }

      // Construct using GrSimReplacement.grSim_Replacement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBallFieldBuilder();
          getRobotsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ballBuilder_ == null) {
          ball_ = null;
        } else {
          ballBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (robotsBuilder_ == null) {
          robots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          robotsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimReplacement.internal_static_grSim_Replacement_descriptor;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_Replacement getDefaultInstanceForType() {
        return GrSimReplacement.grSim_Replacement.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimReplacement.grSim_Replacement build() {
        GrSimReplacement.grSim_Replacement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimReplacement.grSim_Replacement buildPartial() {
        GrSimReplacement.grSim_Replacement result = new GrSimReplacement.grSim_Replacement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (ballBuilder_ == null) {
            result.ball_ = ball_;
          } else {
            result.ball_ = ballBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (robotsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            robots_ = java.util.Collections.unmodifiableList(robots_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.robots_ = robots_;
        } else {
          result.robots_ = robotsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimReplacement.grSim_Replacement) {
          return mergeFrom((GrSimReplacement.grSim_Replacement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimReplacement.grSim_Replacement other) {
        if (other == GrSimReplacement.grSim_Replacement.getDefaultInstance()) return this;
        if (other.hasBall()) {
          mergeBall(other.getBall());
        }
        if (robotsBuilder_ == null) {
          if (!other.robots_.isEmpty()) {
            if (robots_.isEmpty()) {
              robots_ = other.robots_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRobotsIsMutable();
              robots_.addAll(other.robots_);
            }
            onChanged();
          }
        } else {
          if (!other.robots_.isEmpty()) {
            if (robotsBuilder_.isEmpty()) {
              robotsBuilder_.dispose();
              robotsBuilder_ = null;
              robots_ = other.robots_;
              bitField0_ = (bitField0_ & ~0x00000002);
              robotsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRobotsFieldBuilder() : null;
            } else {
              robotsBuilder_.addAllMessages(other.robots_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getRobotsCount(); i++) {
          if (!getRobots(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimReplacement.grSim_Replacement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimReplacement.grSim_Replacement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private GrSimReplacement.grSim_BallReplacement ball_;
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder> ballBuilder_;
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       * @return Whether the ball field is set.
       */
      public boolean hasBall() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       * @return The ball.
       */
      public GrSimReplacement.grSim_BallReplacement getBall() {
        if (ballBuilder_ == null) {
          return ball_ == null ? GrSimReplacement.grSim_BallReplacement.getDefaultInstance() : ball_;
        } else {
          return ballBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public Builder setBall(GrSimReplacement.grSim_BallReplacement value) {
        if (ballBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ball_ = value;
          onChanged();
        } else {
          ballBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public Builder setBall(
          GrSimReplacement.grSim_BallReplacement.Builder builderForValue) {
        if (ballBuilder_ == null) {
          ball_ = builderForValue.build();
          onChanged();
        } else {
          ballBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public Builder mergeBall(GrSimReplacement.grSim_BallReplacement value) {
        if (ballBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              ball_ != null &&
              ball_ != GrSimReplacement.grSim_BallReplacement.getDefaultInstance()) {
            ball_ =
              GrSimReplacement.grSim_BallReplacement.newBuilder(ball_).mergeFrom(value).buildPartial();
          } else {
            ball_ = value;
          }
          onChanged();
        } else {
          ballBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public Builder clearBall() {
        if (ballBuilder_ == null) {
          ball_ = null;
          onChanged();
        } else {
          ballBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public GrSimReplacement.grSim_BallReplacement.Builder getBallBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBallFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      public GrSimReplacement.grSim_BallReplacementOrBuilder getBallOrBuilder() {
        if (ballBuilder_ != null) {
          return ballBuilder_.getMessageOrBuilder();
        } else {
          return ball_ == null ?
              GrSimReplacement.grSim_BallReplacement.getDefaultInstance() : ball_;
        }
      }
      /**
       * <code>optional .grSim_BallReplacement ball = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder> 
          getBallFieldBuilder() {
        if (ballBuilder_ == null) {
          ballBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder>(
                  getBall(),
                  getParentForChildren(),
                  isClean());
          ball_ = null;
        }
        return ballBuilder_;
      }

      private java.util.List<GrSimReplacement.grSim_RobotReplacement> robots_ =
        java.util.Collections.emptyList();
      private void ensureRobotsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          robots_ = new java.util.ArrayList<GrSimReplacement.grSim_RobotReplacement>(robots_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder> robotsBuilder_;

      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public java.util.List<GrSimReplacement.grSim_RobotReplacement> getRobotsList() {
        if (robotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(robots_);
        } else {
          return robotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public int getRobotsCount() {
        if (robotsBuilder_ == null) {
          return robots_.size();
        } else {
          return robotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public GrSimReplacement.grSim_RobotReplacement getRobots(int index) {
        if (robotsBuilder_ == null) {
          return robots_.get(index);
        } else {
          return robotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder setRobots(
          int index, GrSimReplacement.grSim_RobotReplacement value) {
        if (robotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsIsMutable();
          robots_.set(index, value);
          onChanged();
        } else {
          robotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder setRobots(
          int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) {
        if (robotsBuilder_ == null) {
          ensureRobotsIsMutable();
          robots_.set(index, builderForValue.build());
          onChanged();
        } else {
          robotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder addRobots(GrSimReplacement.grSim_RobotReplacement value) {
        if (robotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsIsMutable();
          robots_.add(value);
          onChanged();
        } else {
          robotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder addRobots(
          int index, GrSimReplacement.grSim_RobotReplacement value) {
        if (robotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsIsMutable();
          robots_.add(index, value);
          onChanged();
        } else {
          robotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder addRobots(
          GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) {
        if (robotsBuilder_ == null) {
          ensureRobotsIsMutable();
          robots_.add(builderForValue.build());
          onChanged();
        } else {
          robotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder addRobots(
          int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) {
        if (robotsBuilder_ == null) {
          ensureRobotsIsMutable();
          robots_.add(index, builderForValue.build());
          onChanged();
        } else {
          robotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder addAllRobots(
          java.lang.Iterable<? extends GrSimReplacement.grSim_RobotReplacement> values) {
        if (robotsBuilder_ == null) {
          ensureRobotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, robots_);
          onChanged();
        } else {
          robotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder clearRobots() {
        if (robotsBuilder_ == null) {
          robots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          robotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public Builder removeRobots(int index) {
        if (robotsBuilder_ == null) {
          ensureRobotsIsMutable();
          robots_.remove(index);
          onChanged();
        } else {
          robotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public GrSimReplacement.grSim_RobotReplacement.Builder getRobotsBuilder(
          int index) {
        return getRobotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public GrSimReplacement.grSim_RobotReplacementOrBuilder getRobotsOrBuilder(
          int index) {
        if (robotsBuilder_ == null) {
          return robots_.get(index);  } else {
          return robotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public java.util.List<? extends GrSimReplacement.grSim_RobotReplacementOrBuilder> 
           getRobotsOrBuilderList() {
        if (robotsBuilder_ != null) {
          return robotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(robots_);
        }
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public GrSimReplacement.grSim_RobotReplacement.Builder addRobotsBuilder() {
        return getRobotsFieldBuilder().addBuilder(
            GrSimReplacement.grSim_RobotReplacement.getDefaultInstance());
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public GrSimReplacement.grSim_RobotReplacement.Builder addRobotsBuilder(
          int index) {
        return getRobotsFieldBuilder().addBuilder(
            index, GrSimReplacement.grSim_RobotReplacement.getDefaultInstance());
      }
      /**
       * <code>repeated .grSim_RobotReplacement robots = 2;</code>
       */
      public java.util.List<GrSimReplacement.grSim_RobotReplacement.Builder> 
           getRobotsBuilderList() {
        return getRobotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder> 
          getRobotsFieldBuilder() {
        if (robotsBuilder_ == null) {
          robotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder>(
                  robots_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          robots_ = null;
        }
        return robotsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_Replacement)
    }

    // @@protoc_insertion_point(class_scope:grSim_Replacement)
    private static final GrSimReplacement.grSim_Replacement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimReplacement.grSim_Replacement();
    }

    public static GrSimReplacement.grSim_Replacement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_Replacement>
        PARSER = new com.google.protobuf.AbstractParser<grSim_Replacement>() {
      @java.lang.Override
      public grSim_Replacement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_Replacement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_Replacement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_Replacement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimReplacement.grSim_Replacement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_RobotReplacement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_RobotReplacement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_BallReplacement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_BallReplacement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_Replacement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_Replacement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027grSim_Replacement.proto\"k\n\026grSim_Robot" +
      "Replacement\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\022\013\n\003dir" +
      "\030\003 \002(\001\022\n\n\002id\030\004 \002(\r\022\022\n\nyellowteam\030\005 \002(\010\022\016" +
      "\n\006turnon\030\006 \001(\010\"E\n\025grSim_BallReplacement\022" +
      "\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\n\n\002vx\030\003 \001(\001\022\n\n\002vy\030" +
      "\004 \001(\001\"b\n\021grSim_Replacement\022$\n\004ball\030\001 \001(\013" +
      "2\026.grSim_BallReplacement\022\'\n\006robots\030\002 \003(\013" +
      "2\027.grSim_RobotReplacement"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grSim_RobotReplacement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grSim_RobotReplacement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_RobotReplacement_descriptor,
        new java.lang.String[] { "X", "Y", "Dir", "Id", "Yellowteam", "Turnon", });
    internal_static_grSim_BallReplacement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grSim_BallReplacement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_BallReplacement_descriptor,
        new java.lang.String[] { "X", "Y", "Vx", "Vy", });
    internal_static_grSim_Replacement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grSim_Replacement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_Replacement_descriptor,
        new java.lang.String[] { "Ball", "Robots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
