package Triton.ExternProto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_robot_status.proto

public final class MessagesRobocupSslRobotStatus {
  private MessagesRobocupSslRobotStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Robots_StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Robots_Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    java.util.List<MessagesRobocupSslRobotStatus.Robot_Status> 
        getRobotsStatusList();
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    MessagesRobocupSslRobotStatus.Robot_Status getRobotsStatus(int index);
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    int getRobotsStatusCount();
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    java.util.List<? extends MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder> 
        getRobotsStatusOrBuilderList();
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder getRobotsStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Robots_Status}
   */
  public  static final class Robots_Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Robots_Status)
      Robots_StatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Robots_Status.newBuilder() to construct.
    private Robots_Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Robots_Status() {
      robotsStatus_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Robots_Status();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Robots_Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                robotsStatus_ = new java.util.ArrayList<MessagesRobocupSslRobotStatus.Robot_Status>();
                mutable_bitField0_ |= 0x00000001;
              }
              robotsStatus_.add(
                  input.readMessage(MessagesRobocupSslRobotStatus.Robot_Status.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          robotsStatus_ = java.util.Collections.unmodifiableList(robotsStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesRobocupSslRobotStatus.internal_static_Robots_Status_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesRobocupSslRobotStatus.internal_static_Robots_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagesRobocupSslRobotStatus.Robots_Status.class, MessagesRobocupSslRobotStatus.Robots_Status.Builder.class);
    }

    public static final int ROBOTS_STATUS_FIELD_NUMBER = 1;
    private java.util.List<MessagesRobocupSslRobotStatus.Robot_Status> robotsStatus_;
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    public java.util.List<MessagesRobocupSslRobotStatus.Robot_Status> getRobotsStatusList() {
      return robotsStatus_;
    }
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    public java.util.List<? extends MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder> 
        getRobotsStatusOrBuilderList() {
      return robotsStatus_;
    }
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    public int getRobotsStatusCount() {
      return robotsStatus_.size();
    }
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    public MessagesRobocupSslRobotStatus.Robot_Status getRobotsStatus(int index) {
      return robotsStatus_.get(index);
    }
    /**
     * <code>repeated .Robot_Status robots_status = 1;</code>
     */
    public MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder getRobotsStatusOrBuilder(
        int index) {
      return robotsStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRobotsStatusCount(); i++) {
        if (!getRobotsStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < robotsStatus_.size(); i++) {
        output.writeMessage(1, robotsStatus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < robotsStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, robotsStatus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagesRobocupSslRobotStatus.Robots_Status)) {
        return super.equals(obj);
      }
      MessagesRobocupSslRobotStatus.Robots_Status other = (MessagesRobocupSslRobotStatus.Robots_Status) obj;

      if (!getRobotsStatusList()
          .equals(other.getRobotsStatusList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRobotsStatusCount() > 0) {
        hash = (37 * hash) + ROBOTS_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getRobotsStatusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robots_Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagesRobocupSslRobotStatus.Robots_Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Robots_Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Robots_Status)
        MessagesRobocupSslRobotStatus.Robots_StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesRobocupSslRobotStatus.internal_static_Robots_Status_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesRobocupSslRobotStatus.internal_static_Robots_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagesRobocupSslRobotStatus.Robots_Status.class, MessagesRobocupSslRobotStatus.Robots_Status.Builder.class);
      }

      // Construct using MessagesRobocupSslRobotStatus.Robots_Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRobotsStatusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (robotsStatusBuilder_ == null) {
          robotsStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          robotsStatusBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesRobocupSslRobotStatus.internal_static_Robots_Status_descriptor;
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robots_Status getDefaultInstanceForType() {
        return MessagesRobocupSslRobotStatus.Robots_Status.getDefaultInstance();
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robots_Status build() {
        MessagesRobocupSslRobotStatus.Robots_Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robots_Status buildPartial() {
        MessagesRobocupSslRobotStatus.Robots_Status result = new MessagesRobocupSslRobotStatus.Robots_Status(this);
        int from_bitField0_ = bitField0_;
        if (robotsStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            robotsStatus_ = java.util.Collections.unmodifiableList(robotsStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.robotsStatus_ = robotsStatus_;
        } else {
          result.robotsStatus_ = robotsStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesRobocupSslRobotStatus.Robots_Status) {
          return mergeFrom((MessagesRobocupSslRobotStatus.Robots_Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagesRobocupSslRobotStatus.Robots_Status other) {
        if (other == MessagesRobocupSslRobotStatus.Robots_Status.getDefaultInstance()) return this;
        if (robotsStatusBuilder_ == null) {
          if (!other.robotsStatus_.isEmpty()) {
            if (robotsStatus_.isEmpty()) {
              robotsStatus_ = other.robotsStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRobotsStatusIsMutable();
              robotsStatus_.addAll(other.robotsStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.robotsStatus_.isEmpty()) {
            if (robotsStatusBuilder_.isEmpty()) {
              robotsStatusBuilder_.dispose();
              robotsStatusBuilder_ = null;
              robotsStatus_ = other.robotsStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              robotsStatusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRobotsStatusFieldBuilder() : null;
            } else {
              robotsStatusBuilder_.addAllMessages(other.robotsStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getRobotsStatusCount(); i++) {
          if (!getRobotsStatus(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagesRobocupSslRobotStatus.Robots_Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagesRobocupSslRobotStatus.Robots_Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MessagesRobocupSslRobotStatus.Robot_Status> robotsStatus_ =
        java.util.Collections.emptyList();
      private void ensureRobotsStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          robotsStatus_ = new java.util.ArrayList<MessagesRobocupSslRobotStatus.Robot_Status>(robotsStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MessagesRobocupSslRobotStatus.Robot_Status, MessagesRobocupSslRobotStatus.Robot_Status.Builder, MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder> robotsStatusBuilder_;

      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public java.util.List<MessagesRobocupSslRobotStatus.Robot_Status> getRobotsStatusList() {
        if (robotsStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(robotsStatus_);
        } else {
          return robotsStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public int getRobotsStatusCount() {
        if (robotsStatusBuilder_ == null) {
          return robotsStatus_.size();
        } else {
          return robotsStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public MessagesRobocupSslRobotStatus.Robot_Status getRobotsStatus(int index) {
        if (robotsStatusBuilder_ == null) {
          return robotsStatus_.get(index);
        } else {
          return robotsStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder setRobotsStatus(
          int index, MessagesRobocupSslRobotStatus.Robot_Status value) {
        if (robotsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsStatusIsMutable();
          robotsStatus_.set(index, value);
          onChanged();
        } else {
          robotsStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder setRobotsStatus(
          int index, MessagesRobocupSslRobotStatus.Robot_Status.Builder builderForValue) {
        if (robotsStatusBuilder_ == null) {
          ensureRobotsStatusIsMutable();
          robotsStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          robotsStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder addRobotsStatus(MessagesRobocupSslRobotStatus.Robot_Status value) {
        if (robotsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsStatusIsMutable();
          robotsStatus_.add(value);
          onChanged();
        } else {
          robotsStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder addRobotsStatus(
          int index, MessagesRobocupSslRobotStatus.Robot_Status value) {
        if (robotsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotsStatusIsMutable();
          robotsStatus_.add(index, value);
          onChanged();
        } else {
          robotsStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder addRobotsStatus(
          MessagesRobocupSslRobotStatus.Robot_Status.Builder builderForValue) {
        if (robotsStatusBuilder_ == null) {
          ensureRobotsStatusIsMutable();
          robotsStatus_.add(builderForValue.build());
          onChanged();
        } else {
          robotsStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder addRobotsStatus(
          int index, MessagesRobocupSslRobotStatus.Robot_Status.Builder builderForValue) {
        if (robotsStatusBuilder_ == null) {
          ensureRobotsStatusIsMutable();
          robotsStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          robotsStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder addAllRobotsStatus(
          java.lang.Iterable<? extends MessagesRobocupSslRobotStatus.Robot_Status> values) {
        if (robotsStatusBuilder_ == null) {
          ensureRobotsStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, robotsStatus_);
          onChanged();
        } else {
          robotsStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder clearRobotsStatus() {
        if (robotsStatusBuilder_ == null) {
          robotsStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          robotsStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public Builder removeRobotsStatus(int index) {
        if (robotsStatusBuilder_ == null) {
          ensureRobotsStatusIsMutable();
          robotsStatus_.remove(index);
          onChanged();
        } else {
          robotsStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public MessagesRobocupSslRobotStatus.Robot_Status.Builder getRobotsStatusBuilder(
          int index) {
        return getRobotsStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder getRobotsStatusOrBuilder(
          int index) {
        if (robotsStatusBuilder_ == null) {
          return robotsStatus_.get(index);  } else {
          return robotsStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public java.util.List<? extends MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder> 
           getRobotsStatusOrBuilderList() {
        if (robotsStatusBuilder_ != null) {
          return robotsStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(robotsStatus_);
        }
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public MessagesRobocupSslRobotStatus.Robot_Status.Builder addRobotsStatusBuilder() {
        return getRobotsStatusFieldBuilder().addBuilder(
            MessagesRobocupSslRobotStatus.Robot_Status.getDefaultInstance());
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public MessagesRobocupSslRobotStatus.Robot_Status.Builder addRobotsStatusBuilder(
          int index) {
        return getRobotsStatusFieldBuilder().addBuilder(
            index, MessagesRobocupSslRobotStatus.Robot_Status.getDefaultInstance());
      }
      /**
       * <code>repeated .Robot_Status robots_status = 1;</code>
       */
      public java.util.List<MessagesRobocupSslRobotStatus.Robot_Status.Builder> 
           getRobotsStatusBuilderList() {
        return getRobotsStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MessagesRobocupSslRobotStatus.Robot_Status, MessagesRobocupSslRobotStatus.Robot_Status.Builder, MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder> 
          getRobotsStatusFieldBuilder() {
        if (robotsStatusBuilder_ == null) {
          robotsStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MessagesRobocupSslRobotStatus.Robot_Status, MessagesRobocupSslRobotStatus.Robot_Status.Builder, MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder>(
                  robotsStatus_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          robotsStatus_ = null;
        }
        return robotsStatusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Robots_Status)
    }

    // @@protoc_insertion_point(class_scope:Robots_Status)
    private static final MessagesRobocupSslRobotStatus.Robots_Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagesRobocupSslRobotStatus.Robots_Status();
    }

    public static MessagesRobocupSslRobotStatus.Robots_Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Robots_Status>
        PARSER = new com.google.protobuf.AbstractParser<Robots_Status>() {
      @java.lang.Override
      public Robots_Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Robots_Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Robots_Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Robots_Status> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagesRobocupSslRobotStatus.Robots_Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Robot_StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Robot_Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 robot_id = 1;</code>
     * @return Whether the robotId field is set.
     */
    boolean hasRobotId();
    /**
     * <code>required int32 robot_id = 1;</code>
     * @return The robotId.
     */
    int getRobotId();

    /**
     * <code>required bool infrared = 2;</code>
     * @return Whether the infrared field is set.
     */
    boolean hasInfrared();
    /**
     * <code>required bool infrared = 2;</code>
     * @return The infrared.
     */
    boolean getInfrared();

    /**
     * <code>required bool flat_kick = 3;</code>
     * @return Whether the flatKick field is set.
     */
    boolean hasFlatKick();
    /**
     * <code>required bool flat_kick = 3;</code>
     * @return The flatKick.
     */
    boolean getFlatKick();

    /**
     * <code>required bool chip_kick = 4;</code>
     * @return Whether the chipKick field is set.
     */
    boolean hasChipKick();
    /**
     * <code>required bool chip_kick = 4;</code>
     * @return The chipKick.
     */
    boolean getChipKick();
  }
  /**
   * Protobuf type {@code Robot_Status}
   */
  public  static final class Robot_Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Robot_Status)
      Robot_StatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Robot_Status.newBuilder() to construct.
    private Robot_Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Robot_Status() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Robot_Status();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Robot_Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              robotId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              infrared_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              flatKick_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              chipKick_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesRobocupSslRobotStatus.internal_static_Robot_Status_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesRobocupSslRobotStatus.internal_static_Robot_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagesRobocupSslRobotStatus.Robot_Status.class, MessagesRobocupSslRobotStatus.Robot_Status.Builder.class);
    }

    private int bitField0_;
    public static final int ROBOT_ID_FIELD_NUMBER = 1;
    private int robotId_;
    /**
     * <code>required int32 robot_id = 1;</code>
     * @return Whether the robotId field is set.
     */
    public boolean hasRobotId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 robot_id = 1;</code>
     * @return The robotId.
     */
    public int getRobotId() {
      return robotId_;
    }

    public static final int INFRARED_FIELD_NUMBER = 2;
    private boolean infrared_;
    /**
     * <code>required bool infrared = 2;</code>
     * @return Whether the infrared field is set.
     */
    public boolean hasInfrared() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool infrared = 2;</code>
     * @return The infrared.
     */
    public boolean getInfrared() {
      return infrared_;
    }

    public static final int FLAT_KICK_FIELD_NUMBER = 3;
    private boolean flatKick_;
    /**
     * <code>required bool flat_kick = 3;</code>
     * @return Whether the flatKick field is set.
     */
    public boolean hasFlatKick() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool flat_kick = 3;</code>
     * @return The flatKick.
     */
    public boolean getFlatKick() {
      return flatKick_;
    }

    public static final int CHIP_KICK_FIELD_NUMBER = 4;
    private boolean chipKick_;
    /**
     * <code>required bool chip_kick = 4;</code>
     * @return Whether the chipKick field is set.
     */
    public boolean hasChipKick() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bool chip_kick = 4;</code>
     * @return The chipKick.
     */
    public boolean getChipKick() {
      return chipKick_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRobotId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfrared()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlatKick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChipKick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, robotId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, infrared_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, flatKick_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, chipKick_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, robotId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, infrared_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, flatKick_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, chipKick_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagesRobocupSslRobotStatus.Robot_Status)) {
        return super.equals(obj);
      }
      MessagesRobocupSslRobotStatus.Robot_Status other = (MessagesRobocupSslRobotStatus.Robot_Status) obj;

      if (hasRobotId() != other.hasRobotId()) return false;
      if (hasRobotId()) {
        if (getRobotId()
            != other.getRobotId()) return false;
      }
      if (hasInfrared() != other.hasInfrared()) return false;
      if (hasInfrared()) {
        if (getInfrared()
            != other.getInfrared()) return false;
      }
      if (hasFlatKick() != other.hasFlatKick()) return false;
      if (hasFlatKick()) {
        if (getFlatKick()
            != other.getFlatKick()) return false;
      }
      if (hasChipKick() != other.hasChipKick()) return false;
      if (hasChipKick()) {
        if (getChipKick()
            != other.getChipKick()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRobotId()) {
        hash = (37 * hash) + ROBOT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRobotId();
      }
      if (hasInfrared()) {
        hash = (37 * hash) + INFRARED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getInfrared());
      }
      if (hasFlatKick()) {
        hash = (37 * hash) + FLAT_KICK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getFlatKick());
      }
      if (hasChipKick()) {
        hash = (37 * hash) + CHIP_KICK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getChipKick());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagesRobocupSslRobotStatus.Robot_Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagesRobocupSslRobotStatus.Robot_Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Robot_Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Robot_Status)
        MessagesRobocupSslRobotStatus.Robot_StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesRobocupSslRobotStatus.internal_static_Robot_Status_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesRobocupSslRobotStatus.internal_static_Robot_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagesRobocupSslRobotStatus.Robot_Status.class, MessagesRobocupSslRobotStatus.Robot_Status.Builder.class);
      }

      // Construct using MessagesRobocupSslRobotStatus.Robot_Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        robotId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        infrared_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        flatKick_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        chipKick_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesRobocupSslRobotStatus.internal_static_Robot_Status_descriptor;
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robot_Status getDefaultInstanceForType() {
        return MessagesRobocupSslRobotStatus.Robot_Status.getDefaultInstance();
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robot_Status build() {
        MessagesRobocupSslRobotStatus.Robot_Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessagesRobocupSslRobotStatus.Robot_Status buildPartial() {
        MessagesRobocupSslRobotStatus.Robot_Status result = new MessagesRobocupSslRobotStatus.Robot_Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.robotId_ = robotId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.infrared_ = infrared_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.flatKick_ = flatKick_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.chipKick_ = chipKick_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesRobocupSslRobotStatus.Robot_Status) {
          return mergeFrom((MessagesRobocupSslRobotStatus.Robot_Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagesRobocupSslRobotStatus.Robot_Status other) {
        if (other == MessagesRobocupSslRobotStatus.Robot_Status.getDefaultInstance()) return this;
        if (other.hasRobotId()) {
          setRobotId(other.getRobotId());
        }
        if (other.hasInfrared()) {
          setInfrared(other.getInfrared());
        }
        if (other.hasFlatKick()) {
          setFlatKick(other.getFlatKick());
        }
        if (other.hasChipKick()) {
          setChipKick(other.getChipKick());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRobotId()) {
          return false;
        }
        if (!hasInfrared()) {
          return false;
        }
        if (!hasFlatKick()) {
          return false;
        }
        if (!hasChipKick()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagesRobocupSslRobotStatus.Robot_Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagesRobocupSslRobotStatus.Robot_Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int robotId_ ;
      /**
       * <code>required int32 robot_id = 1;</code>
       * @return Whether the robotId field is set.
       */
      public boolean hasRobotId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 robot_id = 1;</code>
       * @return The robotId.
       */
      public int getRobotId() {
        return robotId_;
      }
      /**
       * <code>required int32 robot_id = 1;</code>
       * @param value The robotId to set.
       * @return This builder for chaining.
       */
      public Builder setRobotId(int value) {
        bitField0_ |= 0x00000001;
        robotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 robot_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRobotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        robotId_ = 0;
        onChanged();
        return this;
      }

      private boolean infrared_ ;
      /**
       * <code>required bool infrared = 2;</code>
       * @return Whether the infrared field is set.
       */
      public boolean hasInfrared() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bool infrared = 2;</code>
       * @return The infrared.
       */
      public boolean getInfrared() {
        return infrared_;
      }
      /**
       * <code>required bool infrared = 2;</code>
       * @param value The infrared to set.
       * @return This builder for chaining.
       */
      public Builder setInfrared(boolean value) {
        bitField0_ |= 0x00000002;
        infrared_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool infrared = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfrared() {
        bitField0_ = (bitField0_ & ~0x00000002);
        infrared_ = false;
        onChanged();
        return this;
      }

      private boolean flatKick_ ;
      /**
       * <code>required bool flat_kick = 3;</code>
       * @return Whether the flatKick field is set.
       */
      public boolean hasFlatKick() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bool flat_kick = 3;</code>
       * @return The flatKick.
       */
      public boolean getFlatKick() {
        return flatKick_;
      }
      /**
       * <code>required bool flat_kick = 3;</code>
       * @param value The flatKick to set.
       * @return This builder for chaining.
       */
      public Builder setFlatKick(boolean value) {
        bitField0_ |= 0x00000004;
        flatKick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool flat_kick = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlatKick() {
        bitField0_ = (bitField0_ & ~0x00000004);
        flatKick_ = false;
        onChanged();
        return this;
      }

      private boolean chipKick_ ;
      /**
       * <code>required bool chip_kick = 4;</code>
       * @return Whether the chipKick field is set.
       */
      public boolean hasChipKick() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required bool chip_kick = 4;</code>
       * @return The chipKick.
       */
      public boolean getChipKick() {
        return chipKick_;
      }
      /**
       * <code>required bool chip_kick = 4;</code>
       * @param value The chipKick to set.
       * @return This builder for chaining.
       */
      public Builder setChipKick(boolean value) {
        bitField0_ |= 0x00000008;
        chipKick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool chip_kick = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChipKick() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chipKick_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Robot_Status)
    }

    // @@protoc_insertion_point(class_scope:Robot_Status)
    private static final MessagesRobocupSslRobotStatus.Robot_Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagesRobocupSslRobotStatus.Robot_Status();
    }

    public static MessagesRobocupSslRobotStatus.Robot_Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Robot_Status>
        PARSER = new com.google.protobuf.AbstractParser<Robot_Status>() {
      @java.lang.Override
      public Robot_Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Robot_Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Robot_Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Robot_Status> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessagesRobocupSslRobotStatus.Robot_Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Robots_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Robots_Status_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Robot_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Robot_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'messages_robocup_ssl_robot_status.prot" +
      "o\"5\n\rRobots_Status\022$\n\rrobots_status\030\001 \003(" +
      "\0132\r.Robot_Status\"X\n\014Robot_Status\022\020\n\010robo" +
      "t_id\030\001 \002(\005\022\020\n\010infrared\030\002 \002(\010\022\021\n\tflat_kic" +
      "k\030\003 \002(\010\022\021\n\tchip_kick\030\004 \002(\010"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Robots_Status_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Robots_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Robots_Status_descriptor,
        new java.lang.String[] { "RobotsStatus", });
    internal_static_Robot_Status_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Robot_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Robot_Status_descriptor,
        new java.lang.String[] { "RobotId", "Infrared", "FlatKick", "ChipKick", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
