package Protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Packet.proto

public final class GrSimPacket {
  private GrSimPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface grSim_PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     * @return Whether the commands field is set.
     */
    boolean hasCommands();
    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     * @return The commands.
     */
    GrSimCommands.grSim_Commands getCommands();
    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     */
    GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder();

    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     * @return Whether the replacement field is set.
     */
    boolean hasReplacement();
    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     * @return The replacement.
     */
    GrSimReplacement.grSim_Replacement getReplacement();
    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     */
    GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder();
  }
  /**
   * Protobuf type {@code grSim_Packet}
   */
  public  static final class grSim_Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_Packet)
      grSim_PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_Packet.newBuilder() to construct.
    private grSim_Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_Packet() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              GrSimCommands.grSim_Commands.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = commands_.toBuilder();
              }
              commands_ = input.readMessage(GrSimCommands.grSim_Commands.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commands_);
                commands_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              GrSimReplacement.grSim_Replacement.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = replacement_.toBuilder();
              }
              replacement_ = input.readMessage(GrSimReplacement.grSim_Replacement.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(replacement_);
                replacement_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimPacket.internal_static_grSim_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimPacket.grSim_Packet.class, GrSimPacket.grSim_Packet.Builder.class);
    }

    private int bitField0_;
    public static final int COMMANDS_FIELD_NUMBER = 1;
    private GrSimCommands.grSim_Commands commands_;
    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     * @return Whether the commands field is set.
     */
    public boolean hasCommands() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     * @return The commands.
     */
    public GrSimCommands.grSim_Commands getCommands() {
      return commands_ == null ? GrSimCommands.grSim_Commands.getDefaultInstance() : commands_;
    }
    /**
     * <code>optional .grSim_Commands commands = 1;</code>
     */
    public GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder() {
      return commands_ == null ? GrSimCommands.grSim_Commands.getDefaultInstance() : commands_;
    }

    public static final int REPLACEMENT_FIELD_NUMBER = 2;
    private GrSimReplacement.grSim_Replacement replacement_;
    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     * @return Whether the replacement field is set.
     */
    public boolean hasReplacement() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     * @return The replacement.
     */
    public GrSimReplacement.grSim_Replacement getReplacement() {
      return replacement_ == null ? GrSimReplacement.grSim_Replacement.getDefaultInstance() : replacement_;
    }
    /**
     * <code>optional .grSim_Replacement replacement = 2;</code>
     */
    public GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder() {
      return replacement_ == null ? GrSimReplacement.grSim_Replacement.getDefaultInstance() : replacement_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasCommands()) {
        if (!getCommands().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasReplacement()) {
        if (!getReplacement().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getCommands());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getReplacement());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommands());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReplacement());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimPacket.grSim_Packet)) {
        return super.equals(obj);
      }
      GrSimPacket.grSim_Packet other = (GrSimPacket.grSim_Packet) obj;

      if (hasCommands() != other.hasCommands()) return false;
      if (hasCommands()) {
        if (!getCommands()
            .equals(other.getCommands())) return false;
      }
      if (hasReplacement() != other.hasReplacement()) return false;
      if (hasReplacement()) {
        if (!getReplacement()
            .equals(other.getReplacement())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommands()) {
        hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
        hash = (53 * hash) + getCommands().hashCode();
      }
      if (hasReplacement()) {
        hash = (37 * hash) + REPLACEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getReplacement().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimPacket.grSim_Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimPacket.grSim_Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimPacket.grSim_Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimPacket.grSim_Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimPacket.grSim_Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimPacket.grSim_Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimPacket.grSim_Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_Packet)
        GrSimPacket.grSim_PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimPacket.internal_static_grSim_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimPacket.grSim_Packet.class, GrSimPacket.grSim_Packet.Builder.class);
      }

      // Construct using GrSimPacket.grSim_Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommandsFieldBuilder();
          getReplacementFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (commandsBuilder_ == null) {
          commands_ = null;
        } else {
          commandsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (replacementBuilder_ == null) {
          replacement_ = null;
        } else {
          replacementBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimPacket.internal_static_grSim_Packet_descriptor;
      }

      @java.lang.Override
      public GrSimPacket.grSim_Packet getDefaultInstanceForType() {
        return GrSimPacket.grSim_Packet.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimPacket.grSim_Packet build() {
        GrSimPacket.grSim_Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimPacket.grSim_Packet buildPartial() {
        GrSimPacket.grSim_Packet result = new GrSimPacket.grSim_Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (commandsBuilder_ == null) {
            result.commands_ = commands_;
          } else {
            result.commands_ = commandsBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (replacementBuilder_ == null) {
            result.replacement_ = replacement_;
          } else {
            result.replacement_ = replacementBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimPacket.grSim_Packet) {
          return mergeFrom((GrSimPacket.grSim_Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimPacket.grSim_Packet other) {
        if (other == GrSimPacket.grSim_Packet.getDefaultInstance()) return this;
        if (other.hasCommands()) {
          mergeCommands(other.getCommands());
        }
        if (other.hasReplacement()) {
          mergeReplacement(other.getReplacement());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasCommands()) {
          if (!getCommands().isInitialized()) {
            return false;
          }
        }
        if (hasReplacement()) {
          if (!getReplacement().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimPacket.grSim_Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimPacket.grSim_Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private GrSimCommands.grSim_Commands commands_;
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder> commandsBuilder_;
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       * @return Whether the commands field is set.
       */
      public boolean hasCommands() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       * @return The commands.
       */
      public GrSimCommands.grSim_Commands getCommands() {
        if (commandsBuilder_ == null) {
          return commands_ == null ? GrSimCommands.grSim_Commands.getDefaultInstance() : commands_;
        } else {
          return commandsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public Builder setCommands(GrSimCommands.grSim_Commands value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commands_ = value;
          onChanged();
        } else {
          commandsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public Builder setCommands(
          GrSimCommands.grSim_Commands.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          commands_ = builderForValue.build();
          onChanged();
        } else {
          commandsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public Builder mergeCommands(GrSimCommands.grSim_Commands value) {
        if (commandsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              commands_ != null &&
              commands_ != GrSimCommands.grSim_Commands.getDefaultInstance()) {
            commands_ =
              GrSimCommands.grSim_Commands.newBuilder(commands_).mergeFrom(value).buildPartial();
          } else {
            commands_ = value;
          }
          onChanged();
        } else {
          commandsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public Builder clearCommands() {
        if (commandsBuilder_ == null) {
          commands_ = null;
          onChanged();
        } else {
          commandsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public GrSimCommands.grSim_Commands.Builder getCommandsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCommandsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      public GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder() {
        if (commandsBuilder_ != null) {
          return commandsBuilder_.getMessageOrBuilder();
        } else {
          return commands_ == null ?
              GrSimCommands.grSim_Commands.getDefaultInstance() : commands_;
        }
      }
      /**
       * <code>optional .grSim_Commands commands = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder> 
          getCommandsFieldBuilder() {
        if (commandsBuilder_ == null) {
          commandsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder>(
                  getCommands(),
                  getParentForChildren(),
                  isClean());
          commands_ = null;
        }
        return commandsBuilder_;
      }

      private GrSimReplacement.grSim_Replacement replacement_;
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder> replacementBuilder_;
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       * @return Whether the replacement field is set.
       */
      public boolean hasReplacement() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       * @return The replacement.
       */
      public GrSimReplacement.grSim_Replacement getReplacement() {
        if (replacementBuilder_ == null) {
          return replacement_ == null ? GrSimReplacement.grSim_Replacement.getDefaultInstance() : replacement_;
        } else {
          return replacementBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public Builder setReplacement(GrSimReplacement.grSim_Replacement value) {
        if (replacementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          replacement_ = value;
          onChanged();
        } else {
          replacementBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public Builder setReplacement(
          GrSimReplacement.grSim_Replacement.Builder builderForValue) {
        if (replacementBuilder_ == null) {
          replacement_ = builderForValue.build();
          onChanged();
        } else {
          replacementBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public Builder mergeReplacement(GrSimReplacement.grSim_Replacement value) {
        if (replacementBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              replacement_ != null &&
              replacement_ != GrSimReplacement.grSim_Replacement.getDefaultInstance()) {
            replacement_ =
              GrSimReplacement.grSim_Replacement.newBuilder(replacement_).mergeFrom(value).buildPartial();
          } else {
            replacement_ = value;
          }
          onChanged();
        } else {
          replacementBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public Builder clearReplacement() {
        if (replacementBuilder_ == null) {
          replacement_ = null;
          onChanged();
        } else {
          replacementBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public GrSimReplacement.grSim_Replacement.Builder getReplacementBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReplacementFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      public GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder() {
        if (replacementBuilder_ != null) {
          return replacementBuilder_.getMessageOrBuilder();
        } else {
          return replacement_ == null ?
              GrSimReplacement.grSim_Replacement.getDefaultInstance() : replacement_;
        }
      }
      /**
       * <code>optional .grSim_Replacement replacement = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder> 
          getReplacementFieldBuilder() {
        if (replacementBuilder_ == null) {
          replacementBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder>(
                  getReplacement(),
                  getParentForChildren(),
                  isClean());
          replacement_ = null;
        }
        return replacementBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_Packet)
    }

    // @@protoc_insertion_point(class_scope:grSim_Packet)
    private static final GrSimPacket.grSim_Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimPacket.grSim_Packet();
    }

    public static GrSimPacket.grSim_Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_Packet>
        PARSER = new com.google.protobuf.AbstractParser<grSim_Packet>() {
      @java.lang.Override
      public grSim_Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimPacket.grSim_Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022grSim_Packet.proto\032\024grSim_Commands.pro" +
      "to\032\027grSim_Replacement.proto\"Z\n\014grSim_Pac" +
      "ket\022!\n\010commands\030\001 \001(\0132\017.grSim_Commands\022\'" +
      "\n\013replacement\030\002 \001(\0132\022.grSim_Replacement"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GrSimCommands.getDescriptor(),
          GrSimReplacement.getDescriptor(),
        });
    internal_static_grSim_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grSim_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_Packet_descriptor,
        new java.lang.String[] { "Commands", "Replacement", });
    GrSimCommands.getDescriptor();
    GrSimReplacement.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
