package Protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Commands.proto

public final class GrSimCommands {
  private GrSimCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface grSim_Robot_CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_Robot_Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required float kickspeedx = 2;</code>
     * @return Whether the kickspeedx field is set.
     */
    boolean hasKickspeedx();
    /**
     * <code>required float kickspeedx = 2;</code>
     * @return The kickspeedx.
     */
    float getKickspeedx();

    /**
     * <code>required float kickspeedz = 3;</code>
     * @return Whether the kickspeedz field is set.
     */
    boolean hasKickspeedz();
    /**
     * <code>required float kickspeedz = 3;</code>
     * @return The kickspeedz.
     */
    float getKickspeedz();

    /**
     * <code>required float veltangent = 4;</code>
     * @return Whether the veltangent field is set.
     */
    boolean hasVeltangent();
    /**
     * <code>required float veltangent = 4;</code>
     * @return The veltangent.
     */
    float getVeltangent();

    /**
     * <code>required float velnormal = 5;</code>
     * @return Whether the velnormal field is set.
     */
    boolean hasVelnormal();
    /**
     * <code>required float velnormal = 5;</code>
     * @return The velnormal.
     */
    float getVelnormal();

    /**
     * <code>required float velangular = 6;</code>
     * @return Whether the velangular field is set.
     */
    boolean hasVelangular();
    /**
     * <code>required float velangular = 6;</code>
     * @return The velangular.
     */
    float getVelangular();

    /**
     * <code>required bool spinner = 7;</code>
     * @return Whether the spinner field is set.
     */
    boolean hasSpinner();
    /**
     * <code>required bool spinner = 7;</code>
     * @return The spinner.
     */
    boolean getSpinner();

    /**
     * <code>required bool wheelsspeed = 8;</code>
     * @return Whether the wheelsspeed field is set.
     */
    boolean hasWheelsspeed();
    /**
     * <code>required bool wheelsspeed = 8;</code>
     * @return The wheelsspeed.
     */
    boolean getWheelsspeed();

    /**
     * <code>optional float wheel1 = 9;</code>
     * @return Whether the wheel1 field is set.
     */
    boolean hasWheel1();
    /**
     * <code>optional float wheel1 = 9;</code>
     * @return The wheel1.
     */
    float getWheel1();

    /**
     * <code>optional float wheel2 = 10;</code>
     * @return Whether the wheel2 field is set.
     */
    boolean hasWheel2();
    /**
     * <code>optional float wheel2 = 10;</code>
     * @return The wheel2.
     */
    float getWheel2();

    /**
     * <code>optional float wheel3 = 11;</code>
     * @return Whether the wheel3 field is set.
     */
    boolean hasWheel3();
    /**
     * <code>optional float wheel3 = 11;</code>
     * @return The wheel3.
     */
    float getWheel3();

    /**
     * <code>optional float wheel4 = 12;</code>
     * @return Whether the wheel4 field is set.
     */
    boolean hasWheel4();
    /**
     * <code>optional float wheel4 = 12;</code>
     * @return The wheel4.
     */
    float getWheel4();
  }
  /**
   * Protobuf type {@code grSim_Robot_Command}
   */
  public  static final class grSim_Robot_Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_Robot_Command)
      grSim_Robot_CommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_Robot_Command.newBuilder() to construct.
    private grSim_Robot_Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_Robot_Command() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_Robot_Command();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_Robot_Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              kickspeedx_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              kickspeedz_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              veltangent_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              velnormal_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              velangular_ = input.readFloat();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              spinner_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              wheelsspeed_ = input.readBool();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              wheel1_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              wheel2_ = input.readFloat();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              wheel3_ = input.readFloat();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000800;
              wheel4_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimCommands.internal_static_grSim_Robot_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimCommands.grSim_Robot_Command.class, GrSimCommands.grSim_Robot_Command.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int KICKSPEEDX_FIELD_NUMBER = 2;
    private float kickspeedx_;
    /**
     * <code>required float kickspeedx = 2;</code>
     * @return Whether the kickspeedx field is set.
     */
    public boolean hasKickspeedx() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required float kickspeedx = 2;</code>
     * @return The kickspeedx.
     */
    public float getKickspeedx() {
      return kickspeedx_;
    }

    public static final int KICKSPEEDZ_FIELD_NUMBER = 3;
    private float kickspeedz_;
    /**
     * <code>required float kickspeedz = 3;</code>
     * @return Whether the kickspeedz field is set.
     */
    public boolean hasKickspeedz() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float kickspeedz = 3;</code>
     * @return The kickspeedz.
     */
    public float getKickspeedz() {
      return kickspeedz_;
    }

    public static final int VELTANGENT_FIELD_NUMBER = 4;
    private float veltangent_;
    /**
     * <code>required float veltangent = 4;</code>
     * @return Whether the veltangent field is set.
     */
    public boolean hasVeltangent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required float veltangent = 4;</code>
     * @return The veltangent.
     */
    public float getVeltangent() {
      return veltangent_;
    }

    public static final int VELNORMAL_FIELD_NUMBER = 5;
    private float velnormal_;
    /**
     * <code>required float velnormal = 5;</code>
     * @return Whether the velnormal field is set.
     */
    public boolean hasVelnormal() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required float velnormal = 5;</code>
     * @return The velnormal.
     */
    public float getVelnormal() {
      return velnormal_;
    }

    public static final int VELANGULAR_FIELD_NUMBER = 6;
    private float velangular_;
    /**
     * <code>required float velangular = 6;</code>
     * @return Whether the velangular field is set.
     */
    public boolean hasVelangular() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required float velangular = 6;</code>
     * @return The velangular.
     */
    public float getVelangular() {
      return velangular_;
    }

    public static final int SPINNER_FIELD_NUMBER = 7;
    private boolean spinner_;
    /**
     * <code>required bool spinner = 7;</code>
     * @return Whether the spinner field is set.
     */
    public boolean hasSpinner() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required bool spinner = 7;</code>
     * @return The spinner.
     */
    public boolean getSpinner() {
      return spinner_;
    }

    public static final int WHEELSSPEED_FIELD_NUMBER = 8;
    private boolean wheelsspeed_;
    /**
     * <code>required bool wheelsspeed = 8;</code>
     * @return Whether the wheelsspeed field is set.
     */
    public boolean hasWheelsspeed() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>required bool wheelsspeed = 8;</code>
     * @return The wheelsspeed.
     */
    public boolean getWheelsspeed() {
      return wheelsspeed_;
    }

    public static final int WHEEL1_FIELD_NUMBER = 9;
    private float wheel1_;
    /**
     * <code>optional float wheel1 = 9;</code>
     * @return Whether the wheel1 field is set.
     */
    public boolean hasWheel1() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional float wheel1 = 9;</code>
     * @return The wheel1.
     */
    public float getWheel1() {
      return wheel1_;
    }

    public static final int WHEEL2_FIELD_NUMBER = 10;
    private float wheel2_;
    /**
     * <code>optional float wheel2 = 10;</code>
     * @return Whether the wheel2 field is set.
     */
    public boolean hasWheel2() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional float wheel2 = 10;</code>
     * @return The wheel2.
     */
    public float getWheel2() {
      return wheel2_;
    }

    public static final int WHEEL3_FIELD_NUMBER = 11;
    private float wheel3_;
    /**
     * <code>optional float wheel3 = 11;</code>
     * @return Whether the wheel3 field is set.
     */
    public boolean hasWheel3() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional float wheel3 = 11;</code>
     * @return The wheel3.
     */
    public float getWheel3() {
      return wheel3_;
    }

    public static final int WHEEL4_FIELD_NUMBER = 12;
    private float wheel4_;
    /**
     * <code>optional float wheel4 = 12;</code>
     * @return Whether the wheel4 field is set.
     */
    public boolean hasWheel4() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional float wheel4 = 12;</code>
     * @return The wheel4.
     */
    public float getWheel4() {
      return wheel4_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKickspeedx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKickspeedz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVeltangent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVelnormal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVelangular()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpinner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWheelsspeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, kickspeedx_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, kickspeedz_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(4, veltangent_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, velnormal_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFloat(6, velangular_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(7, spinner_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBool(8, wheelsspeed_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeFloat(9, wheel1_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeFloat(10, wheel2_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeFloat(11, wheel3_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeFloat(12, wheel4_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, kickspeedx_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, kickspeedz_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, veltangent_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, velnormal_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, velangular_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, spinner_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, wheelsspeed_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, wheel1_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, wheel2_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, wheel3_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, wheel4_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimCommands.grSim_Robot_Command)) {
        return super.equals(obj);
      }
      GrSimCommands.grSim_Robot_Command other = (GrSimCommands.grSim_Robot_Command) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasKickspeedx() != other.hasKickspeedx()) return false;
      if (hasKickspeedx()) {
        if (java.lang.Float.floatToIntBits(getKickspeedx())
            != java.lang.Float.floatToIntBits(
                other.getKickspeedx())) return false;
      }
      if (hasKickspeedz() != other.hasKickspeedz()) return false;
      if (hasKickspeedz()) {
        if (java.lang.Float.floatToIntBits(getKickspeedz())
            != java.lang.Float.floatToIntBits(
                other.getKickspeedz())) return false;
      }
      if (hasVeltangent() != other.hasVeltangent()) return false;
      if (hasVeltangent()) {
        if (java.lang.Float.floatToIntBits(getVeltangent())
            != java.lang.Float.floatToIntBits(
                other.getVeltangent())) return false;
      }
      if (hasVelnormal() != other.hasVelnormal()) return false;
      if (hasVelnormal()) {
        if (java.lang.Float.floatToIntBits(getVelnormal())
            != java.lang.Float.floatToIntBits(
                other.getVelnormal())) return false;
      }
      if (hasVelangular() != other.hasVelangular()) return false;
      if (hasVelangular()) {
        if (java.lang.Float.floatToIntBits(getVelangular())
            != java.lang.Float.floatToIntBits(
                other.getVelangular())) return false;
      }
      if (hasSpinner() != other.hasSpinner()) return false;
      if (hasSpinner()) {
        if (getSpinner()
            != other.getSpinner()) return false;
      }
      if (hasWheelsspeed() != other.hasWheelsspeed()) return false;
      if (hasWheelsspeed()) {
        if (getWheelsspeed()
            != other.getWheelsspeed()) return false;
      }
      if (hasWheel1() != other.hasWheel1()) return false;
      if (hasWheel1()) {
        if (java.lang.Float.floatToIntBits(getWheel1())
            != java.lang.Float.floatToIntBits(
                other.getWheel1())) return false;
      }
      if (hasWheel2() != other.hasWheel2()) return false;
      if (hasWheel2()) {
        if (java.lang.Float.floatToIntBits(getWheel2())
            != java.lang.Float.floatToIntBits(
                other.getWheel2())) return false;
      }
      if (hasWheel3() != other.hasWheel3()) return false;
      if (hasWheel3()) {
        if (java.lang.Float.floatToIntBits(getWheel3())
            != java.lang.Float.floatToIntBits(
                other.getWheel3())) return false;
      }
      if (hasWheel4() != other.hasWheel4()) return false;
      if (hasWheel4()) {
        if (java.lang.Float.floatToIntBits(getWheel4())
            != java.lang.Float.floatToIntBits(
                other.getWheel4())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasKickspeedx()) {
        hash = (37 * hash) + KICKSPEEDX_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getKickspeedx());
      }
      if (hasKickspeedz()) {
        hash = (37 * hash) + KICKSPEEDZ_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getKickspeedz());
      }
      if (hasVeltangent()) {
        hash = (37 * hash) + VELTANGENT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getVeltangent());
      }
      if (hasVelnormal()) {
        hash = (37 * hash) + VELNORMAL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getVelnormal());
      }
      if (hasVelangular()) {
        hash = (37 * hash) + VELANGULAR_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getVelangular());
      }
      if (hasSpinner()) {
        hash = (37 * hash) + SPINNER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSpinner());
      }
      if (hasWheelsspeed()) {
        hash = (37 * hash) + WHEELSSPEED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getWheelsspeed());
      }
      if (hasWheel1()) {
        hash = (37 * hash) + WHEEL1_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWheel1());
      }
      if (hasWheel2()) {
        hash = (37 * hash) + WHEEL2_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWheel2());
      }
      if (hasWheel3()) {
        hash = (37 * hash) + WHEEL3_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWheel3());
      }
      if (hasWheel4()) {
        hash = (37 * hash) + WHEEL4_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWheel4());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimCommands.grSim_Robot_Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimCommands.grSim_Robot_Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Robot_Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Robot_Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimCommands.grSim_Robot_Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_Robot_Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_Robot_Command)
        GrSimCommands.grSim_Robot_CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimCommands.internal_static_grSim_Robot_Command_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimCommands.grSim_Robot_Command.class, GrSimCommands.grSim_Robot_Command.Builder.class);
      }

      // Construct using GrSimCommands.grSim_Robot_Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        kickspeedx_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        kickspeedz_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        veltangent_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        velnormal_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        velangular_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        spinner_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        wheelsspeed_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        wheel1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        wheel2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        wheel3_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000400);
        wheel4_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimCommands.internal_static_grSim_Robot_Command_descriptor;
      }

      @java.lang.Override
      public GrSimCommands.grSim_Robot_Command getDefaultInstanceForType() {
        return GrSimCommands.grSim_Robot_Command.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimCommands.grSim_Robot_Command build() {
        GrSimCommands.grSim_Robot_Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimCommands.grSim_Robot_Command buildPartial() {
        GrSimCommands.grSim_Robot_Command result = new GrSimCommands.grSim_Robot_Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.kickspeedx_ = kickspeedx_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.kickspeedz_ = kickspeedz_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.veltangent_ = veltangent_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.velnormal_ = velnormal_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.velangular_ = velangular_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.spinner_ = spinner_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.wheelsspeed_ = wheelsspeed_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.wheel1_ = wheel1_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.wheel2_ = wheel2_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.wheel3_ = wheel3_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.wheel4_ = wheel4_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimCommands.grSim_Robot_Command) {
          return mergeFrom((GrSimCommands.grSim_Robot_Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimCommands.grSim_Robot_Command other) {
        if (other == GrSimCommands.grSim_Robot_Command.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasKickspeedx()) {
          setKickspeedx(other.getKickspeedx());
        }
        if (other.hasKickspeedz()) {
          setKickspeedz(other.getKickspeedz());
        }
        if (other.hasVeltangent()) {
          setVeltangent(other.getVeltangent());
        }
        if (other.hasVelnormal()) {
          setVelnormal(other.getVelnormal());
        }
        if (other.hasVelangular()) {
          setVelangular(other.getVelangular());
        }
        if (other.hasSpinner()) {
          setSpinner(other.getSpinner());
        }
        if (other.hasWheelsspeed()) {
          setWheelsspeed(other.getWheelsspeed());
        }
        if (other.hasWheel1()) {
          setWheel1(other.getWheel1());
        }
        if (other.hasWheel2()) {
          setWheel2(other.getWheel2());
        }
        if (other.hasWheel3()) {
          setWheel3(other.getWheel3());
        }
        if (other.hasWheel4()) {
          setWheel4(other.getWheel4());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasKickspeedx()) {
          return false;
        }
        if (!hasKickspeedz()) {
          return false;
        }
        if (!hasVeltangent()) {
          return false;
        }
        if (!hasVelnormal()) {
          return false;
        }
        if (!hasVelangular()) {
          return false;
        }
        if (!hasSpinner()) {
          return false;
        }
        if (!hasWheelsspeed()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimCommands.grSim_Robot_Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimCommands.grSim_Robot_Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private float kickspeedx_ ;
      /**
       * <code>required float kickspeedx = 2;</code>
       * @return Whether the kickspeedx field is set.
       */
      public boolean hasKickspeedx() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required float kickspeedx = 2;</code>
       * @return The kickspeedx.
       */
      public float getKickspeedx() {
        return kickspeedx_;
      }
      /**
       * <code>required float kickspeedx = 2;</code>
       * @param value The kickspeedx to set.
       * @return This builder for chaining.
       */
      public Builder setKickspeedx(float value) {
        bitField0_ |= 0x00000002;
        kickspeedx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float kickspeedx = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKickspeedx() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kickspeedx_ = 0F;
        onChanged();
        return this;
      }

      private float kickspeedz_ ;
      /**
       * <code>required float kickspeedz = 3;</code>
       * @return Whether the kickspeedz field is set.
       */
      public boolean hasKickspeedz() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float kickspeedz = 3;</code>
       * @return The kickspeedz.
       */
      public float getKickspeedz() {
        return kickspeedz_;
      }
      /**
       * <code>required float kickspeedz = 3;</code>
       * @param value The kickspeedz to set.
       * @return This builder for chaining.
       */
      public Builder setKickspeedz(float value) {
        bitField0_ |= 0x00000004;
        kickspeedz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float kickspeedz = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKickspeedz() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kickspeedz_ = 0F;
        onChanged();
        return this;
      }

      private float veltangent_ ;
      /**
       * <code>required float veltangent = 4;</code>
       * @return Whether the veltangent field is set.
       */
      public boolean hasVeltangent() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required float veltangent = 4;</code>
       * @return The veltangent.
       */
      public float getVeltangent() {
        return veltangent_;
      }
      /**
       * <code>required float veltangent = 4;</code>
       * @param value The veltangent to set.
       * @return This builder for chaining.
       */
      public Builder setVeltangent(float value) {
        bitField0_ |= 0x00000008;
        veltangent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float veltangent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVeltangent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        veltangent_ = 0F;
        onChanged();
        return this;
      }

      private float velnormal_ ;
      /**
       * <code>required float velnormal = 5;</code>
       * @return Whether the velnormal field is set.
       */
      public boolean hasVelnormal() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required float velnormal = 5;</code>
       * @return The velnormal.
       */
      public float getVelnormal() {
        return velnormal_;
      }
      /**
       * <code>required float velnormal = 5;</code>
       * @param value The velnormal to set.
       * @return This builder for chaining.
       */
      public Builder setVelnormal(float value) {
        bitField0_ |= 0x00000010;
        velnormal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float velnormal = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVelnormal() {
        bitField0_ = (bitField0_ & ~0x00000010);
        velnormal_ = 0F;
        onChanged();
        return this;
      }

      private float velangular_ ;
      /**
       * <code>required float velangular = 6;</code>
       * @return Whether the velangular field is set.
       */
      public boolean hasVelangular() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required float velangular = 6;</code>
       * @return The velangular.
       */
      public float getVelangular() {
        return velangular_;
      }
      /**
       * <code>required float velangular = 6;</code>
       * @param value The velangular to set.
       * @return This builder for chaining.
       */
      public Builder setVelangular(float value) {
        bitField0_ |= 0x00000020;
        velangular_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float velangular = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVelangular() {
        bitField0_ = (bitField0_ & ~0x00000020);
        velangular_ = 0F;
        onChanged();
        return this;
      }

      private boolean spinner_ ;
      /**
       * <code>required bool spinner = 7;</code>
       * @return Whether the spinner field is set.
       */
      public boolean hasSpinner() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required bool spinner = 7;</code>
       * @return The spinner.
       */
      public boolean getSpinner() {
        return spinner_;
      }
      /**
       * <code>required bool spinner = 7;</code>
       * @param value The spinner to set.
       * @return This builder for chaining.
       */
      public Builder setSpinner(boolean value) {
        bitField0_ |= 0x00000040;
        spinner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool spinner = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpinner() {
        bitField0_ = (bitField0_ & ~0x00000040);
        spinner_ = false;
        onChanged();
        return this;
      }

      private boolean wheelsspeed_ ;
      /**
       * <code>required bool wheelsspeed = 8;</code>
       * @return Whether the wheelsspeed field is set.
       */
      public boolean hasWheelsspeed() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>required bool wheelsspeed = 8;</code>
       * @return The wheelsspeed.
       */
      public boolean getWheelsspeed() {
        return wheelsspeed_;
      }
      /**
       * <code>required bool wheelsspeed = 8;</code>
       * @param value The wheelsspeed to set.
       * @return This builder for chaining.
       */
      public Builder setWheelsspeed(boolean value) {
        bitField0_ |= 0x00000080;
        wheelsspeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool wheelsspeed = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearWheelsspeed() {
        bitField0_ = (bitField0_ & ~0x00000080);
        wheelsspeed_ = false;
        onChanged();
        return this;
      }

      private float wheel1_ ;
      /**
       * <code>optional float wheel1 = 9;</code>
       * @return Whether the wheel1 field is set.
       */
      public boolean hasWheel1() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional float wheel1 = 9;</code>
       * @return The wheel1.
       */
      public float getWheel1() {
        return wheel1_;
      }
      /**
       * <code>optional float wheel1 = 9;</code>
       * @param value The wheel1 to set.
       * @return This builder for chaining.
       */
      public Builder setWheel1(float value) {
        bitField0_ |= 0x00000100;
        wheel1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float wheel1 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearWheel1() {
        bitField0_ = (bitField0_ & ~0x00000100);
        wheel1_ = 0F;
        onChanged();
        return this;
      }

      private float wheel2_ ;
      /**
       * <code>optional float wheel2 = 10;</code>
       * @return Whether the wheel2 field is set.
       */
      public boolean hasWheel2() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional float wheel2 = 10;</code>
       * @return The wheel2.
       */
      public float getWheel2() {
        return wheel2_;
      }
      /**
       * <code>optional float wheel2 = 10;</code>
       * @param value The wheel2 to set.
       * @return This builder for chaining.
       */
      public Builder setWheel2(float value) {
        bitField0_ |= 0x00000200;
        wheel2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float wheel2 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearWheel2() {
        bitField0_ = (bitField0_ & ~0x00000200);
        wheel2_ = 0F;
        onChanged();
        return this;
      }

      private float wheel3_ ;
      /**
       * <code>optional float wheel3 = 11;</code>
       * @return Whether the wheel3 field is set.
       */
      public boolean hasWheel3() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional float wheel3 = 11;</code>
       * @return The wheel3.
       */
      public float getWheel3() {
        return wheel3_;
      }
      /**
       * <code>optional float wheel3 = 11;</code>
       * @param value The wheel3 to set.
       * @return This builder for chaining.
       */
      public Builder setWheel3(float value) {
        bitField0_ |= 0x00000400;
        wheel3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float wheel3 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearWheel3() {
        bitField0_ = (bitField0_ & ~0x00000400);
        wheel3_ = 0F;
        onChanged();
        return this;
      }

      private float wheel4_ ;
      /**
       * <code>optional float wheel4 = 12;</code>
       * @return Whether the wheel4 field is set.
       */
      public boolean hasWheel4() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional float wheel4 = 12;</code>
       * @return The wheel4.
       */
      public float getWheel4() {
        return wheel4_;
      }
      /**
       * <code>optional float wheel4 = 12;</code>
       * @param value The wheel4 to set.
       * @return This builder for chaining.
       */
      public Builder setWheel4(float value) {
        bitField0_ |= 0x00000800;
        wheel4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float wheel4 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearWheel4() {
        bitField0_ = (bitField0_ & ~0x00000800);
        wheel4_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_Robot_Command)
    }

    // @@protoc_insertion_point(class_scope:grSim_Robot_Command)
    private static final GrSimCommands.grSim_Robot_Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimCommands.grSim_Robot_Command();
    }

    public static GrSimCommands.grSim_Robot_Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_Robot_Command>
        PARSER = new com.google.protobuf.AbstractParser<grSim_Robot_Command>() {
      @java.lang.Override
      public grSim_Robot_Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_Robot_Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_Robot_Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_Robot_Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimCommands.grSim_Robot_Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface grSim_CommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grSim_Commands)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>required double timestamp = 1;</code>
     * @return The timestamp.
     */
    double getTimestamp();

    /**
     * <code>required bool isteamyellow = 2;</code>
     * @return Whether the isteamyellow field is set.
     */
    boolean hasIsteamyellow();
    /**
     * <code>required bool isteamyellow = 2;</code>
     * @return The isteamyellow.
     */
    boolean getIsteamyellow();

    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    java.util.List<GrSimCommands.grSim_Robot_Command> 
        getRobotCommandsList();
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    GrSimCommands.grSim_Robot_Command getRobotCommands(int index);
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    int getRobotCommandsCount();
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    java.util.List<? extends GrSimCommands.grSim_Robot_CommandOrBuilder> 
        getRobotCommandsOrBuilderList();
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    GrSimCommands.grSim_Robot_CommandOrBuilder getRobotCommandsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code grSim_Commands}
   */
  public  static final class grSim_Commands extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grSim_Commands)
      grSim_CommandsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use grSim_Commands.newBuilder() to construct.
    private grSim_Commands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private grSim_Commands() {
      robotCommands_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new grSim_Commands();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private grSim_Commands(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readDouble();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isteamyellow_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                robotCommands_ = new java.util.ArrayList<GrSimCommands.grSim_Robot_Command>();
                mutable_bitField0_ |= 0x00000004;
              }
              robotCommands_.add(
                  input.readMessage(GrSimCommands.grSim_Robot_Command.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          robotCommands_ = java.util.Collections.unmodifiableList(robotCommands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrSimCommands.internal_static_grSim_Commands_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrSimCommands.grSim_Commands.class, GrSimCommands.grSim_Commands.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private double timestamp_;
    /**
     * <code>required double timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double timestamp = 1;</code>
     * @return The timestamp.
     */
    public double getTimestamp() {
      return timestamp_;
    }

    public static final int ISTEAMYELLOW_FIELD_NUMBER = 2;
    private boolean isteamyellow_;
    /**
     * <code>required bool isteamyellow = 2;</code>
     * @return Whether the isteamyellow field is set.
     */
    public boolean hasIsteamyellow() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool isteamyellow = 2;</code>
     * @return The isteamyellow.
     */
    public boolean getIsteamyellow() {
      return isteamyellow_;
    }

    public static final int ROBOT_COMMANDS_FIELD_NUMBER = 3;
    private java.util.List<GrSimCommands.grSim_Robot_Command> robotCommands_;
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    public java.util.List<GrSimCommands.grSim_Robot_Command> getRobotCommandsList() {
      return robotCommands_;
    }
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    public java.util.List<? extends GrSimCommands.grSim_Robot_CommandOrBuilder> 
        getRobotCommandsOrBuilderList() {
      return robotCommands_;
    }
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    public int getRobotCommandsCount() {
      return robotCommands_.size();
    }
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    public GrSimCommands.grSim_Robot_Command getRobotCommands(int index) {
      return robotCommands_.get(index);
    }
    /**
     * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
     */
    public GrSimCommands.grSim_Robot_CommandOrBuilder getRobotCommandsOrBuilder(
        int index) {
      return robotCommands_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsteamyellow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRobotCommandsCount(); i++) {
        if (!getRobotCommands(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, isteamyellow_);
      }
      for (int i = 0; i < robotCommands_.size(); i++) {
        output.writeMessage(3, robotCommands_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isteamyellow_);
      }
      for (int i = 0; i < robotCommands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, robotCommands_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrSimCommands.grSim_Commands)) {
        return super.equals(obj);
      }
      GrSimCommands.grSim_Commands other = (GrSimCommands.grSim_Commands) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (java.lang.Double.doubleToLongBits(getTimestamp())
            != java.lang.Double.doubleToLongBits(
                other.getTimestamp())) return false;
      }
      if (hasIsteamyellow() != other.hasIsteamyellow()) return false;
      if (hasIsteamyellow()) {
        if (getIsteamyellow()
            != other.getIsteamyellow()) return false;
      }
      if (!getRobotCommandsList()
          .equals(other.getRobotCommandsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getTimestamp()));
      }
      if (hasIsteamyellow()) {
        hash = (37 * hash) + ISTEAMYELLOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsteamyellow());
      }
      if (getRobotCommandsCount() > 0) {
        hash = (37 * hash) + ROBOT_COMMANDS_FIELD_NUMBER;
        hash = (53 * hash) + getRobotCommandsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrSimCommands.grSim_Commands parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Commands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrSimCommands.grSim_Commands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimCommands.grSim_Commands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Commands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrSimCommands.grSim_Commands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrSimCommands.grSim_Commands prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grSim_Commands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grSim_Commands)
        GrSimCommands.grSim_CommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrSimCommands.internal_static_grSim_Commands_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrSimCommands.grSim_Commands.class, GrSimCommands.grSim_Commands.Builder.class);
      }

      // Construct using GrSimCommands.grSim_Commands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRobotCommandsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        isteamyellow_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (robotCommandsBuilder_ == null) {
          robotCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          robotCommandsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrSimCommands.internal_static_grSim_Commands_descriptor;
      }

      @java.lang.Override
      public GrSimCommands.grSim_Commands getDefaultInstanceForType() {
        return GrSimCommands.grSim_Commands.getDefaultInstance();
      }

      @java.lang.Override
      public GrSimCommands.grSim_Commands build() {
        GrSimCommands.grSim_Commands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrSimCommands.grSim_Commands buildPartial() {
        GrSimCommands.grSim_Commands result = new GrSimCommands.grSim_Commands(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isteamyellow_ = isteamyellow_;
          to_bitField0_ |= 0x00000002;
        }
        if (robotCommandsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            robotCommands_ = java.util.Collections.unmodifiableList(robotCommands_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.robotCommands_ = robotCommands_;
        } else {
          result.robotCommands_ = robotCommandsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrSimCommands.grSim_Commands) {
          return mergeFrom((GrSimCommands.grSim_Commands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrSimCommands.grSim_Commands other) {
        if (other == GrSimCommands.grSim_Commands.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIsteamyellow()) {
          setIsteamyellow(other.getIsteamyellow());
        }
        if (robotCommandsBuilder_ == null) {
          if (!other.robotCommands_.isEmpty()) {
            if (robotCommands_.isEmpty()) {
              robotCommands_ = other.robotCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRobotCommandsIsMutable();
              robotCommands_.addAll(other.robotCommands_);
            }
            onChanged();
          }
        } else {
          if (!other.robotCommands_.isEmpty()) {
            if (robotCommandsBuilder_.isEmpty()) {
              robotCommandsBuilder_.dispose();
              robotCommandsBuilder_ = null;
              robotCommands_ = other.robotCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
              robotCommandsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRobotCommandsFieldBuilder() : null;
            } else {
              robotCommandsBuilder_.addAllMessages(other.robotCommands_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasIsteamyellow()) {
          return false;
        }
        for (int i = 0; i < getRobotCommandsCount(); i++) {
          if (!getRobotCommands(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrSimCommands.grSim_Commands parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrSimCommands.grSim_Commands) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double timestamp_ ;
      /**
       * <code>required double timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double timestamp = 1;</code>
       * @return The timestamp.
       */
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required double timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(double value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      private boolean isteamyellow_ ;
      /**
       * <code>required bool isteamyellow = 2;</code>
       * @return Whether the isteamyellow field is set.
       */
      public boolean hasIsteamyellow() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bool isteamyellow = 2;</code>
       * @return The isteamyellow.
       */
      public boolean getIsteamyellow() {
        return isteamyellow_;
      }
      /**
       * <code>required bool isteamyellow = 2;</code>
       * @param value The isteamyellow to set.
       * @return This builder for chaining.
       */
      public Builder setIsteamyellow(boolean value) {
        bitField0_ |= 0x00000002;
        isteamyellow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isteamyellow = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsteamyellow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isteamyellow_ = false;
        onChanged();
        return this;
      }

      private java.util.List<GrSimCommands.grSim_Robot_Command> robotCommands_ =
        java.util.Collections.emptyList();
      private void ensureRobotCommandsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          robotCommands_ = new java.util.ArrayList<GrSimCommands.grSim_Robot_Command>(robotCommands_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder> robotCommandsBuilder_;

      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<GrSimCommands.grSim_Robot_Command> getRobotCommandsList() {
        if (robotCommandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(robotCommands_);
        } else {
          return robotCommandsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public int getRobotCommandsCount() {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.size();
        } else {
          return robotCommandsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public GrSimCommands.grSim_Robot_Command getRobotCommands(int index) {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.get(index);
        } else {
          return robotCommandsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder setRobotCommands(
          int index, GrSimCommands.grSim_Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.set(index, value);
          onChanged();
        } else {
          robotCommandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder setRobotCommands(
          int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.set(index, builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(GrSimCommands.grSim_Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.add(value);
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          int index, GrSimCommands.grSim_Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.add(index, value);
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          GrSimCommands.grSim_Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.add(builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.add(index, builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder addAllRobotCommands(
          java.lang.Iterable<? extends GrSimCommands.grSim_Robot_Command> values) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, robotCommands_);
          onChanged();
        } else {
          robotCommandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder clearRobotCommands() {
        if (robotCommandsBuilder_ == null) {
          robotCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          robotCommandsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public Builder removeRobotCommands(int index) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.remove(index);
          onChanged();
        } else {
          robotCommandsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public GrSimCommands.grSim_Robot_Command.Builder getRobotCommandsBuilder(
          int index) {
        return getRobotCommandsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public GrSimCommands.grSim_Robot_CommandOrBuilder getRobotCommandsOrBuilder(
          int index) {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.get(index);  } else {
          return robotCommandsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<? extends GrSimCommands.grSim_Robot_CommandOrBuilder> 
           getRobotCommandsOrBuilderList() {
        if (robotCommandsBuilder_ != null) {
          return robotCommandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(robotCommands_);
        }
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public GrSimCommands.grSim_Robot_Command.Builder addRobotCommandsBuilder() {
        return getRobotCommandsFieldBuilder().addBuilder(
            GrSimCommands.grSim_Robot_Command.getDefaultInstance());
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public GrSimCommands.grSim_Robot_Command.Builder addRobotCommandsBuilder(
          int index) {
        return getRobotCommandsFieldBuilder().addBuilder(
            index, GrSimCommands.grSim_Robot_Command.getDefaultInstance());
      }
      /**
       * <code>repeated .grSim_Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<GrSimCommands.grSim_Robot_Command.Builder> 
           getRobotCommandsBuilderList() {
        return getRobotCommandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder> 
          getRobotCommandsFieldBuilder() {
        if (robotCommandsBuilder_ == null) {
          robotCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder>(
                  robotCommands_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          robotCommands_ = null;
        }
        return robotCommandsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grSim_Commands)
    }

    // @@protoc_insertion_point(class_scope:grSim_Commands)
    private static final GrSimCommands.grSim_Commands DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrSimCommands.grSim_Commands();
    }

    public static GrSimCommands.grSim_Commands getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<grSim_Commands>
        PARSER = new com.google.protobuf.AbstractParser<grSim_Commands>() {
      @java.lang.Override
      public grSim_Commands parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new grSim_Commands(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<grSim_Commands> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<grSim_Commands> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrSimCommands.grSim_Commands getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_Robot_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_Robot_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grSim_Commands_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grSim_Commands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024grSim_Commands.proto\"\352\001\n\023grSim_Robot_C" +
      "ommand\022\n\n\002id\030\001 \002(\r\022\022\n\nkickspeedx\030\002 \002(\002\022\022" +
      "\n\nkickspeedz\030\003 \002(\002\022\022\n\nveltangent\030\004 \002(\002\022\021" +
      "\n\tvelnormal\030\005 \002(\002\022\022\n\nvelangular\030\006 \002(\002\022\017\n" +
      "\007spinner\030\007 \002(\010\022\023\n\013wheelsspeed\030\010 \002(\010\022\016\n\006w" +
      "heel1\030\t \001(\002\022\016\n\006wheel2\030\n \001(\002\022\016\n\006wheel3\030\013 " +
      "\001(\002\022\016\n\006wheel4\030\014 \001(\002\"g\n\016grSim_Commands\022\021\n" +
      "\ttimestamp\030\001 \002(\001\022\024\n\014isteamyellow\030\002 \002(\010\022," +
      "\n\016robot_commands\030\003 \003(\0132\024.grSim_Robot_Com" +
      "mand"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grSim_Robot_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grSim_Robot_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_Robot_Command_descriptor,
        new java.lang.String[] { "Id", "Kickspeedx", "Kickspeedz", "Veltangent", "Velnormal", "Velangular", "Spinner", "Wheelsspeed", "Wheel1", "Wheel2", "Wheel3", "Wheel4", });
    internal_static_grSim_Commands_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grSim_Commands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grSim_Commands_descriptor,
        new java.lang.String[] { "Timestamp", "Isteamyellow", "RobotCommands", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
